spring:
  application:
    name: greffecare-api

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/greffecare
    username: greffecare
    password: greffecare

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/master

server:
  port: 8081
